name: Deploy to Vercel

on:
  push:
    branches:
      - vercel-connection

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Authenticate with Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel login --token $VERCEL_TOKEN

      - name: Create new Vercel project
        id: create-project
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          response=$(curl -X POST https://api.vercel.com/v9/projects \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"name\": \"${GITHUB_REPOSITORY}-$(date +%s)\",
              \"framework\": \"nextjs\",
              \"orgId\": \"$VERCEL_ORG_ID\"
            }")
          echo $response
          project_id=$(echo $response | jq -r '.id')
          echo "project_id=$project_id" >> $GITHUB_ENV

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          PROJECT_ID: ${{ env.project_id }}
        run: vercel --prod --token $VERCEL_TOKEN --confirm --project-id $PROJECT_ID
