name: Deploy to Vercel (New Project)
on:
  push:
    branches:
      - vercel-connection-test
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Vercel CLI
      run: npm install -g vercel
    
    - name: Generate unique project name
      id: project-name
      run: echo "name=my-project-$(date +%s)" >> $GITHUB_OUTPUT
    
    - name: Create new Vercel project
      id: create-project
      run: |
        # Create new project and capture the project ID
        PROJECT_ID=$(vercel project add "${{ steps.project-name.outputs.name }}" --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_ORG_ID }})
        echo "id=$PROJECT_ID" >> $GITHUB_OUTPUT
    
    - name: Create vercel.json
      run: |
        echo '{
          "name": "${{ steps.project-name.outputs.name }}",
          "framework": "python"
        }' > vercel.json
    
    - name: Deploy to new Vercel project
      run: |
        vercel --yes --token ${{ secrets.VERCEL_TOKEN }} --prod
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ steps.create-project.outputs.id }}
