name: Vercel Deploy on Push

on:
  push:
    branches:
      - vercel-connection-test  # Trigger this workflow on pushes to this branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Or whatever Node.js version you use

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Configure Vercel with GitHub Secrets
        run: |
          vercel login --token ${{ secrets.VERCEL_TOKEN }}
          vercel link --org ${{ secrets.VERCEL_ORG_ID }}

      - name: Create Vercel Project (Optional)
        run: |
          # Create a new project on Vercel using the Vercel API or CLI
          PROJECT_NAME="vercel-project-${{ github.sha }}" # You can use a custom name
          vercel init --confirm --name $PROJECT_NAME

      - name: Deploy to Vercel
        run: |
          vercel --token ${{ secrets.VERCEL_TOKEN }} --org ${{ secrets.VERCEL_ORG_ID }} --prod

